# Generated by Django 5.1.6 on 2025-02-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(db_index=True, max_length=300),
        ),
    ]
